### ISSUE TITLE
Make the buildpacks accessible for use by OSS CF users

### ISSUE THREAD

**Issue by mogul** [newrelic/newrelic-dotnet-buildpack-tile#1]
Hello,

You're bundling up and releasing all the buildpacks up in a tile file, which is specific to Pivotal's flavor of Cloud Foundry. However, there's nothing about the actual buildpacks that is specific to PCF, and there are likely many users of the open source Cloud Foundry distribution who would be happy to make use of New Relic with their dotnet apps.

Can you please make the buildpacks available from this repository directly under `Releases`? You can see that other standard buildpack repositories do this:

- https://github.com/cloudfoundry/dotnet-core-buildpack/releases
- https://github.com/cloudfoundry/php-buildpack/releases
- https://github.com/cloudfoundry/ruby-buildpack/releases

I'm thinking in particular of `releases/packages/nr_dotnet_core_buildpack/dotnet_core_buildpack-vX.Y.Z-nr.zip`. If you do this, then we we can just tell our customers to use `-b URL-TO-THIS-REPOSITORY` when pushing their applications to use the New Relic buildpack rather than have to reinterpret directions, unpack the files, etc.

Thanks,
Bret

**Comment by shahramk** [comment]
apologies for not attending this repo for some time. The purpose of this repo was mainly to make the tile available which as you know contains all the extension buildpacks. 

Individual extension buildpacks could easily be extracted from the downloaded zip file. we will consider making the extension buildpacks available directly under releases in upcoming releases.

thank you
shahram
