### ISSUE TITLE
Publish buildpack zip files on github

### ISSUE THREAD

**Issue by mikepedeupe** [newrelic/newrelic-dotnet-buildpack-tile#4]
Hello.  In the previous release, you also included direct links to download the built buildpack zip files.  We are able to include these zip files in the Cloud Foundry buildpack list directly.  Can you publish the individual zips in this release, like you did in the previous release?

**Comment by josephlocascio** [comment]
@mikepedeupe this has been released!

**Comment by shahramk** [comment]
buildpack 1.1.6 binary is always available for download at https://network.pivotal.io/products/new-relic-dotnet-buildpack/.
It is now available also on this github repo: https://github.com/newrelic/newrelic-dotnet-buildpack-tile/releases/tag/v1.1.6.
